module.exports = {
    NotSpecified: 'NotSpecified',
    MARKETPLACE: 'MARKETPLACE',
    P2P_PAYMENT: 'P2P_PAYMENT',
    CROWDFUNDING_DONATION: 'CROWDFUNDING_DONATION',
    CROWDFUNDING_REWARD: 'CROWDFUNDING_REWARD',
    CROWDFUNDING_EQUITY: 'CROWDFUNDING_EQUITY',
    CROWDFUNDING_LOAN: 'CROWDFUNDING_LOAN',
    OTHER: 'OTHER'
};
